#!/bin/sh
set -eu

print_success() { printf "\033[32m%s\033[0m\n" "$1"; }
print_error()   { printf "\033[31m%s\033[0m\n" "$1"; }
print_warn()    { printf "\033[33m%s\033[0m\n" "$1"; }
print_info()    { printf "\033[36m%s\033[0m\n" "$1"; }

# Must be root
if [ "$(id -u)" -ne 0 ]; then
  print_error "Run as root: sudo sh $0"
  exit 1
fi

PHP_BIN="/usr/bin/php8.4"
PHP_CONFIG="/usr/bin/php-config8.4"
PHPIZE="/usr/bin/phpize8.4"
FPM_SERVICE="php8.4-fpm"
SCRIPT_DIR="\"(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\""
ESL_SO_SRC="$SCRIPT_DIR/esl-8.4.so"
FS_SRC="/usr/src/freeswitch"

ARCH="$(uname -m)"
print_info "Detected architecture: $ARCH"

if [ ! -x "$PHP_BIN" ]; then
  print_error "php8.4 not found at $PHP_BIN"
  exit 1
fi

for ini in \
    /etc/php/8.4/cli/conf.d/30-esl.ini \
    /etc/php/8.4/fpm/conf.d/30-esl.ini; do
  [ -f "$ini" ] && rm -f "$ini" && print_info "Removed stale: $ini"
done

EXTENSION_DIR="$($PHP_BIN -r 'echo ini_get("extension_dir");')"
if [ -z "$EXTENSION_DIR" ]; then
  print_error "Failed to detect PHP 8.4 extension_dir."
  exit 1
fi
print_success "PHP 8.4 extension_dir: $EXTENSION_DIR"

detect_swig_php_flag() {
  SWIG_VER="$(swig -version 2>&1 | awk '/SWIG Version/{print $3}')"
  print_info "Detected SWIG version: $SWIG_VER"
  SWIG_MAJOR="$(printf '%s' "$SWIG_VER" | cut -d. -f1)"
  SWIG_MINOR="$(printf '%s' "$SWIG_VER" | cut -d. -f2)"
  if [ "$SWIG_MAJOR" -gt 4 ] || { [ "$SWIG_MAJOR" -eq 4 ] && [ "$SWIG_MINOR" -ge 1 ]; }; then
    SWIG_PHP_FLAG="-php"
    print_info "Using SWIG flag: -php  (SWIG >= 4.1)"
  else
    SWIG_PHP_FLAG="-php8"
    print_info "Using SWIG flag: -php8  (SWIG < 4.1)"
  fi
}

ensure_freeswitch_source() {
  ESL_DIR="$FS_SRC/libs/esl"
  ESL_INC_DIR="$ESL_DIR/src/include"
  HEADERS_OK=true
  for f in "$ESL_DIR/ESL.i" "$ESL_INC_DIR/esl_oop.h" "$ESL_INC_DIR/esl.h"; do
    [ -f "$f" ] || HEADERS_OK=false
  done
  if [ "$HEADERS_OK" = false ]; then
    if [ -d "$FS_SRC" ]; then
      print_warn "FreeSWITCH source incomplete -- removing and re-cloning..."
      rm -rf "$FS_SRC"
    else
      print_info "Cloning FreeSWITCH source..."
    fi
    git clone --depth=1 --recurse-submodules --shallow-submodules \
      https://github.com/signalwire/freeswitch.git "$FS_SRC"
  else
    print_info "FreeSWITCH source OK at: $FS_SRC"
    return
  fi
  for f in "$ESL_DIR/ESL.i" "$ESL_INC_DIR/esl_oop.h" "$ESL_INC_DIR/esl.h"; do
    if [ ! -f "$f" ]; then
      print_error "Required file still missing after clone: $f"
      exit 1
    fi
  done
  print_success "All required ESL source files verified."
}

# Replace the ./libtool generated by config.status (which is built from the
# old FreeSWITCH ltmain.sh and does not understand --tag=CXX or many modern
# flags) with a small wrapper that strips --tag=* and then delegates every
# call to the real system libtool binary installed via apt.
# Called AFTER ./configure (so config.status has written ./libtool) and
# BEFORE make (so nothing overwrites the wrapper).
replace_libtool_with_wrapper() {
  _lt="$1"

  # Find the real system libtool binary
  _sys_lt=""
  for _c in /usr/bin/libtool /usr/local/bin/libtool; do
    [ -x "$_c" ] && _sys_lt="$_c" && break
  done

  if [ -z "$_sys_lt" ]; then
    print_warn "System libtool binary not found -- falling back to in-place --tag strip patch."
    _tag_strip_patch "$_lt"
    return
  fi

  print_info "Replacing generated libtool with wrapper around $_sys_lt ..."
  _real="$_sys_lt"
  printf '#!/bin/sh\n# libtool wrapper: strips --tag=* then calls real system libtool\n' > "$_lt"
  printf '_w_real="%s"\n' "$_real" >> "$_lt"
  printf '_w_args=""\n' >> "$_lt"
  printf 'for _w_a in "$@"; do\n' >> "$_lt"
  printf '  case "$ _w_a" in --tag=*) ;; *) _w_args="$_w_args".$_w_args:+ }${_w_a}";; esac\n' >> "$_lt"
  printf 'done\n' >> "$_lt"
  printf '# shellcheck disable=SC2086\n' >> "$_lt"
  printf 'exec "$ _w_real" $__w_args\n' >> "$_lt"
  chmod +x "$_lt"
  print_success "Replaced generated libtool with wrapper."
}

# Fallback: in-place patch to strip --tag=* from the generated libtool script.
_tag_strip_patch() {
  _lt="$1"
  if [ ! -f "$_lt" ]; then
    print_warn "Generated libtool not found at $_lt -- skipping patch."
    return
  fi
  if grep -q 'COPILOT_TAG_PATCH' "$_lt"; then
    print_info "Generated libtool already patched -- skipping."
    return
  fi
  print_info "Applying --tag strip patch to generated libtool ..."
  _tmp="${_lt}.tmp$$"
  head -n 1 "$_lt" > "$_tmp"
  printf '%s\n' \
    '' \
    '# COPILOT_TAG_PATCH begin' \
    '_ctp_i=0; _ctp_total=$#' \
    'while [ "$ _ctp_i" -lt "$ _ctp_total" ]; do' \
    '  _ctp_a="$1"; shift; _ctp_i=$((_ctp_i + 1))' \
    '  case "$ _ctp_a" in --tag=*) ;; *) set -- "$@" "$ _ctp_a" ;; esac' \
    'done' \
    'unset _ctp_a _ctp_i _ctp_total' \
    '# COPILOT_TAG_PATCH end' \
    '' >> "$ _tmp"
  tail -n +2 "$_lt" >> "$ _tmp"
  mv "$ _tmp" "$_lt"
  chmod +x "$_lt"
  print_success "Generated libtool patched."
}

build_esl_from_source() {
  print_info "ARM64 detected -- building ESL PHP extension from source..."

  apt-get update -qq
  apt-get install -y --no-install-recommends \
    php8.4-dev swig build-essential git ca-certificates autoconf libtool

  detect_swig_php_flag
  ensure_freeswitch_source

  ESL_DIR="$FS_SRC/libs/esl"
  ESL_SRC_DIR="$ESL_DIR/src"
  ESL_INC_DIR="$ESL_SRC_DIR/include"
  PHP_EXT_DIR="$ESL_DIR/php"

  if [ ! -d "$PHP_EXT_DIR" ]; then
    print_error "PHP extension dir not found: $PHP_EXT_DIR"
    ls -la "$ESL_DIR" || true
    exit 1
  fi

  print_info "Regenerating SWIG bindings..."
  cd "$ESL_DIR"
  swig "$SWIG_PHP_FLAG" -c++ -module esl -cppext cpp \
       -I"$ESL_DIR" -I"$ESL_SRC_DIR" -I"$ESL_INC_DIR" \
       -o "$PHP_EXT_DIR/ESL.cpp" -outdir "$PHP_EXT_DIR" \
       "$ESL_DIR/ESL.i"
  print_success "SWIG bindings generated."

  if [ ! -f "$PHP_EXT_DIR/config.m4" ]; then
    print_info "Generating config.m4..."
    cat > "$PHP_EXT_DIR/config.m4" << 'M4EOF'
PHP_ARG_ENABLE(esl, whether to enable ESL support,
[  --enable-esl            Enable ESL support])

if test "$PHP_ESL" != "no"; then
  PHP_NEW_EXTENSION(esl, ESL.cpp, $ext_shared)
fi
M4EOF
    print_success "config.m4 generated."
  fi

  print_info "Running phpize in $PHP_EXT_DIR ..."
  cd "$PHP_EXT_DIR"
  if [ -f Makefile ]; then
    make distclean 2>/dev/null || make clean 2>/dev/null || true
  fi
  "$PHPIZE" --clean 2>/dev/null || true
  "$PHPIZE"

  print_info "Running configure..."
  CPPFLAGS="-I$ESL_DIR -I$ESL_SRC_DIR -I$ESL_INC_DIR" \
    ./configure --with-php-config="${PHP_CONFIG}"

  # Replace the generated libtool with a wrapper around the real system one
  replace_libtool_with_wrapper "$PHP_EXT_DIR/libtool"

  print_info "Running make..."
  make -j"$(nproc)" CPPFLAGS="-I$ESL_DIR -I$ESL_SRC_DIR -I$ESL_INC_DIR"

  BUILT_SO=""
  for candidate in "$PHP_EXT_DIR/modules/esl.so" "$PHP_EXT_DIR/.libs/esl.so"; do
    [ -f "$candidate" ] && BUILT_SO="$candidate" && break
  done

  if [ -z "$BUILT_SO" ]; then
    print_error "Build finished but esl.so not found."
    ls -la "$PHP_EXT_DIR/" || true
    ls -la "$PHP_EXT_DIR/modules/" 2>/dev/null || true
    exit 1
  fi

  print_info "Found built module: $BUILT_SO"

  SO_FILE_OUTPUT="$(file "$BUILT_SO")"
  print_info "Built binary info: $SO_FILE_OUTPUT"
  case "$SO_FILE_OUTPUT" in
    *aarch64*|*ARM\ aarch64*) print_success "Architecture verified: aarch64" ;;
    *) print_error "Built .so does not appear to be aarch64: $SO_FILE_OUTPUT"; exit 1 ;;
  esac

  if ldd "$BUILT_SO" 2>&1 | grep -q "not found"; then
    print_error "Missing shared library dependencies:"
    ldd "$BUILT_SO" | grep "not found"
    exit 1
  fi
  print_success "ldd check passed -- no missing dependencies."

  ESL_SO_SRC="$BUILT_SO"
}

case "$ARCH" in
  aarch64|arm64)
    build_esl_from_source
    ;;
  x86_64|amd64)
    if [ ! -f "$ESL_SO_SRC" ]; then
      print_error "Missing ESL module: $ESL_SO_SRC"
      print_error "Place your compiled module at: /var/www/fspbx/install/esl-8.4.so"
      exit 1
    fi
    SO_FILE_OUTPUT="$(file "$ESL_SO_SRC")"
    case "$SO_FILE_OUTPUT" in
      *x86-64*|*x86_64*) print_success "Pre-built binary architecture verified: x86_64" ;;
      *) print_error "Pre-built .so is not x86_64: $SO_FILE_OUTPUT"; exit 1 ;;
    esac
    ;;
  *)
    print_error "Unsupported architecture: $ARCH"
    exit 1 ;;
 esac

install -m 0644 -o root -g root "$ESL_SO_SRC" "$EXTENSION_DIR/esl.so"
print_success "Installed: $EXTENSION_DIR/esl.so"

CLI_INI_DIR="/etc/php/8.4/cli/conf.d"
FPM_INI_DIR="/etc/php/8.4/fpm/conf.d"
mkdir -p "$CLI_INI_DIR" "$FPM_INI_DIR"
echo "extension=esl.so" > "$CLI_INI_DIR/30-esl.ini"
echo "extension=esl.so" > "$FPM_INI_DIR/30-esl.ini"
print_success "Enabled ESL in $CLI_INI_DIR/30-esl.ini and $FPM_INI_DIR/30-esl.ini"

if command -v systemctl >/dev/null 2>&1; then
  systemctl restart "$FPM_SERVICE"
else
  service "$FPM_SERVICE" restart
fi
print_success "Restarted: $FPM_SERVICE"

if "$PHP_BIN" -m | grep -qi '^esl$'; then
  print_success "ESL loaded in PHP 8.4 (CLI)."
else
  print_error "ESL did not load in PHP 8.4."
  print_warn "Check: ldd \"$EXTENSION_DIR/esl.so\""
  exit 1
fi

print_success "ESL installation completed successfully for PHP 8.4 on $ARCH.
"